spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: jiancc
    password: jiancc_123!D
    url: jdbc:mysql://47.101.173.181/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
